In [1]:
%cd ..

/home/jupyter-tim/ba-tim


In [14]:
from drlqap.taskgenerators import generators
import scipy.optimize
from drlqap.simplesolver import solve_qap_backtracking, solve_qap_maxgreedy, solve_qap_faq, solve_random
from drlqap.gurobi import solve_qap_gurobi
import numpy as np
from drlqap.qap import QAP
from drlqap.evaltools import load_checkpoints
from pathlib import Path

In [143]:
medium_agents = load_checkpoints(Path('runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1'))
small_agents = load_checkpoints(Path('runs/dqn_dense_ms_ec_eps0_smallrandoms/lr5e-4_s1'))
mini_agents = load_checkpoints(Path('runs/dqn_dense_ms_ec_eps0_mini/lr5e-4_s1'))

runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_0.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_1000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_2000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_3000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_4000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_5000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_6000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_7000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_8000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_9000.pth
runs/dqn_dense_ms_ec_eps0_mediumrandoms/lr5e-4_s1/checkpoint_end.pth
runs/dqn_dense_ms_ec_eps0_smallrandoms/lr5e-4_s1/checkpoint_0.pth
runs/dqn_dense_ms_ec_eps0_smallrandoms/lr5e-4_s1/checkpoint_1000.pth
runs/dqn_dense_ms_ec_eps0_smallrandoms/lr5e-4_s1/checkpoint_2000.pth
runs/dqn_dense_ms_ec_eps0_smal

In [136]:
def evaluate(solver, problem, samples):
    values = []
    correct = 0
    for i in range(samples):
        qap = generators[problem].sample()
        if qap.compute_value([0,1]) < qap.compute_value([1,0]):
            optimum = [0,1]
        else:
            optimum = [1,0]
        v_solver, assignment = solver(qap)
        v = qap.compute_value(assignment)
        if v != v_solver:
            print (f"solver outputs incorrect value (got {v_solver}, actual {v})")
        if np.any(np.array(assignment) == np.array(optimum)):
            correct += 1
        values.append(v)
    print("mean:", np.mean(values))
    print("correct:", correct)
    print("accuracy:", correct/samples)

In [130]:
evaluate(solve_qap_backtracking, 'minilinear', 1000)

mean: 0.7576946
correct: 1000
accuracy: 1.0


In [131]:
evaluate(solve_random, 'minilinear', 1000)

mean: 0.9979258
correct: 520
accuracy: 0.52


In [132]:
evaluate(solve_qap_faq, 'minilinear', 1000)

solver outputs incorrect value (got 0.0, actual 1.5207195281982422)
solver outputs incorrect value (got 0.0, actual 0.7753775715827942)
solver outputs incorrect value (got 0.0, actual 1.1803607940673828)
solver outputs incorrect value (got 0.0, actual 0.8000912070274353)
solver outputs incorrect value (got 0.0, actual 1.2202997207641602)
solver outputs incorrect value (got 0.0, actual 0.6490228772163391)
solver outputs incorrect value (got 0.0, actual 1.6138384342193604)
solver outputs incorrect value (got 0.0, actual 1.754654049873352)
solver outputs incorrect value (got 0.0, actual 1.230531930923462)
solver outputs incorrect value (got 0.0, actual 0.7635549902915955)
solver outputs incorrect value (got 0.0, actual 0.6047475337982178)
solver outputs incorrect value (got 0.0, actual 1.093785047531128)
solver outputs incorrect value (got 0.0, actual 0.8659074902534485)
solver outputs incorrect value (got 0.0, actual 1.586484670639038)
solver outputs incorrect value (got 0.0, actual 0.69

solver outputs incorrect value (got 0.0, actual 0.3583434224128723)
solver outputs incorrect value (got 0.0, actual 0.6863373517990112)
solver outputs incorrect value (got 0.0, actual 1.260765552520752)
solver outputs incorrect value (got 0.0, actual 1.2583091259002686)
solver outputs incorrect value (got 0.0, actual 0.8466415405273438)
solver outputs incorrect value (got 0.0, actual 1.0129789113998413)
solver outputs incorrect value (got 0.0, actual 1.4044394493103027)
solver outputs incorrect value (got 0.0, actual 1.6805822849273682)
solver outputs incorrect value (got 0.0, actual 0.974123477935791)
solver outputs incorrect value (got 0.0, actual 1.5042152404785156)
solver outputs incorrect value (got 0.0, actual 1.0380866527557373)
solver outputs incorrect value (got 0.0, actual 1.3453257083892822)
solver outputs incorrect value (got 0.0, actual 0.9302020072937012)
solver outputs incorrect value (got 0.0, actual 0.4061276316642761)
solver outputs incorrect value (got 0.0, actual 0.

solver outputs incorrect value (got 0.0, actual 1.4944429397583008)
solver outputs incorrect value (got 0.0, actual 1.1590633392333984)
solver outputs incorrect value (got 0.0, actual 0.9874622225761414)
solver outputs incorrect value (got 0.0, actual 0.9650232195854187)
solver outputs incorrect value (got 0.0, actual 1.2058022022247314)
solver outputs incorrect value (got 0.0, actual 1.354137659072876)
solver outputs incorrect value (got 0.0, actual 1.0920979976654053)
solver outputs incorrect value (got 0.0, actual 1.1130578517913818)
solver outputs incorrect value (got 0.0, actual 1.0792388916015625)
solver outputs incorrect value (got 0.0, actual 1.0670487880706787)
solver outputs incorrect value (got 0.0, actual 0.2094360589981079)
solver outputs incorrect value (got 0.0, actual 0.6207605600357056)
solver outputs incorrect value (got 0.0, actual 0.8248220682144165)
solver outputs incorrect value (got 0.0, actual 0.22783714532852173)
solver outputs incorrect value (got 0.0, actual 

solver outputs incorrect value (got 0.0, actual 1.3095879554748535)
solver outputs incorrect value (got 0.0, actual 0.28928422927856445)
solver outputs incorrect value (got 0.0, actual 0.6471645832061768)
solver outputs incorrect value (got 0.0, actual 1.62435781955719)
solver outputs incorrect value (got 0.0, actual 1.2850382328033447)
solver outputs incorrect value (got 0.0, actual 0.3993353843688965)
solver outputs incorrect value (got 0.0, actual 1.3713542222976685)
solver outputs incorrect value (got 0.0, actual 1.0193421840667725)
solver outputs incorrect value (got 0.0, actual 0.8967289924621582)
solver outputs incorrect value (got 0.0, actual 1.2886680364608765)
solver outputs incorrect value (got 0.0, actual 1.5035390853881836)
solver outputs incorrect value (got 0.0, actual 0.35140687227249146)
solver outputs incorrect value (got 0.0, actual 0.4801114797592163)
solver outputs incorrect value (got 0.0, actual 1.3423316478729248)
solver outputs incorrect value (got 0.0, actual 

solver outputs incorrect value (got 0.0, actual 0.6324858665466309)
solver outputs incorrect value (got 0.0, actual 0.46518510580062866)
solver outputs incorrect value (got 0.0, actual 1.0042978525161743)
solver outputs incorrect value (got 0.0, actual 1.4130008220672607)
solver outputs incorrect value (got 0.0, actual 1.4876596927642822)
solver outputs incorrect value (got 0.0, actual 1.2916839122772217)
solver outputs incorrect value (got 0.0, actual 1.1224665641784668)
solver outputs incorrect value (got 0.0, actual 1.5946118831634521)
solver outputs incorrect value (got 0.0, actual 1.502756118774414)
solver outputs incorrect value (got 0.0, actual 0.8769543170928955)
solver outputs incorrect value (got 0.0, actual 0.14046186208724976)
solver outputs incorrect value (got 0.0, actual 1.2014195919036865)
solver outputs incorrect value (got 0.0, actual 1.5702718496322632)
solver outputs incorrect value (got 0.0, actual 1.0748887062072754)
solver outputs incorrect value (got 0.0, actual

In [156]:
evaluate(mini_agents[1].solve, 'minilinear', 1000)

mean: 0.7773864
correct: 937
accuracy: 0.937


In [157]:
evaluate(small_agents[1].solve, 'minilinear', 1000)

mean: 0.938606
correct: 596
accuracy: 0.596


In [158]:
evaluate(medium_agents[1].solve, 'minilinear', 1000)

mean: 1.0175263
correct: 479
accuracy: 0.479


In [134]:
qap = generators['minilinear'].sample()

In [100]:
print(qap.A)
print(qap.B)
print(qap.linear_costs)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.2239, 0.3953],
        [0.7601, 0.8479]])


In [101]:
qap.compute_value([0,1])

tensor(1.0718)

In [102]:
qap.compute_value([1,0])

tensor(1.1554)

In [103]:
agents[-1].solve(qap)

(1.071818768978119, [0, 1])